### PR TITLE
Add search function and search test.

### PR DESCRIPTION
**Pull request by amykangweb**
Added search functions and test for search.

### CODE REVIEW

**Comment by amykangweb** [comment]
Search only returns published and non private deals.

**Comment by amykangweb** [comment]
Sorry about the merge conflict commits. I had to resolve merge conflicts when pulling from master then resolve merge conflicts between my search-bar branch and master branch.

**Comment by marythought** [comment]
FYI our internet went down!

**Comment by amykangweb** [comment]
Okay.

**Pull request merged**
